### ISSUE TITLE
Check ROM validity

### ISSUE THREAD

**Issue by jeffXvX** [jeffXvX/Wheel-of-Fortune-Maker#15]
Make sure the ROM that's uploaded has the right hash

**Comment by tme321** [comment]
A basic framework for errors with both the ability to show dialogs and an errors log in side the app has been added.  These are both very basic for now but the groundwork has been laid so that it can be expanded as needed later.

The checksum of the supplied ROM is compared against the known good checksum and an error is displayed and logged if they do not match.  While this could certainly be made to look nicer and such the functionality works so I'm closing this one.  If we want to later we can create another issue about restyling in general.
