### ISSUE TITLE
title screen

### ISSUE THREAD

**Issue by jeffXvX** [jeffXvX/Wheel-of-Fortune-Maker#17]
Change the text on the title screen to reflect the game name, and potentially also allow the user to add in their name as well. also add some text to the effect of "made with WoF Maker" or something like that

**Comment by tme321** [comment]
Do you have the memory locations and encoding methods of where this stuff is stored in the rom?

**Comment by jeffXvX** [comment]
Scrolling text on intro screen is at $0462 -$4aa
Uses A-Z and commas instead of spaces
As an example, here's what I have in the Gamer Edition ROM:
GAMER,EDITION,CREATED,,BY,JEFFXVX,,,,,SPECIAL,THANKS,LOZCARDSFAN23,,,,,,,

Intro screen is at $d47-$db8
Uses A-Z; commas instead of spaces. There are three lines. The last character of the first line has the high bit set and is then followed by #21 #86. The second last character of the second line has the high bit set and is then followed by #21 #a4. 

As an example, here's what I have in the Gamer Edition ROM
for $d47-$d8b:
,,,GAMER,,EDITION,,BÙ!†,,,,,JEFFXVØ!¤,SPECIAL,THANKS,LOZCARDSFAN,,,,,

**Comment by tme321** [comment]
Ok so using this I successfully created an interface for modifying both the scrolling text at the bottom and the intro text lines.

I think there might be some small bug related to the spacing, or possibly some control character I'm missing or something because the copyright line on the intro screen is being pulled up?  Like the line is still there but it's almost like there is a missing newline character or something.

But it doesn't really seem to affect anything.  I can still run through an entire game.  And the text I supplied works.

Also, the interface isn't anything to write home about.  But so far that's pretty true for all our interfaces.

For now though, this feature is "complete" enough that I am moving on.  If you want to open another bug about how the spacing is working on the intro screen I'll address it then but I think it is in a good enough position for now to close this issue.
